### PR TITLE
Updated astropy-helpers to v1.0.2

### PR DESCRIPTION
**Pull request by cdeil**
This should fix `python setup.py build_sphinx` for Sphinx 1.3+.

### CODE REVIEW

**Comment by cdeil** [comment]
There's a bunch of different build errors on travis-ci due to various reasons:
https://travis-ci.org/astrofrog/reproject/builds/59570921

I'll try to change the `.travis.yml` and code now to make it pass again.

**Comment by astrofrog** [comment]
Thanks! I think some of the imports of ``wcs_utils`` will need to be fixed for Travis to pass.

**Comment by cdeil** [comment]
@astrofrog I wasn't sure how to replace all function calls with things to `astropy.wcs`.
Do you want to make a PR against this one, or should I just put the parts of `wcs_utils` back here and then someone can replace this with `astropy.wcs` later?

**Comment by astrofrog** [comment]
@cdeil - maybe revert those changes for now, and I can work on that on my train journey today :)

**Comment by cdeil** [comment]
@astrofrog – I removed the changes to `wcs_utils` from this PR. Should be OK now.

**Comment by astrofrog** [comment]
@cdeil - perfect, thanks!

**Comment by astrofrog** [comment]
Working on the WCS changes now.

**Pull request merged**
