### PR TITLE
Remove numpy 1.7 and 1.8

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by bsipocz** [comment]
Failures against the dev astropy is unrelated and are due to a DeprecationWarning coming from ``pytest-arraydiff`` for which PR https://github.com/astrofrog/pytest-arraydiff/pull/10 was opened (but is failing atm as it doesn't yet handle astropy <2.0).

**Comment by bsipocz** [comment]
For a change, this probably will now fail for old astropy versions.

**Comment by bsipocz** [comment]
Finally this passes!

**Comment by astrofrog** [comment]
Thanks!

**Pull request merged**
