### PR TITLE
Patch C to compile on Windows and add appveyor testing

### PR DESCRIPTION
**Pull request by mwcraig**
@astrofrog -- this will require you to flip the switch on appveyor.

Right now this uses `ci-helpers` for appveyor but not travis...I assume I should switch travis to that also before this is merged (which would mean not merging #91 I assume).

### CODE REVIEW

**Comment by mwcraig** [comment]
@astrofrog -- never mind about the appveyor switch, it is already running!

**Comment by astrofrog** [comment]
Travis is failing because of issues that were fixed in ``ci-helpers`` - I'll fix that in a separate PR.

**Comment by astrofrog** [comment]
See https://github.com/astrofrog/reproject/pull/94 - once that is merged, this PR will need to be rebased.

**Comment by astrofrog** [comment]
@mwcraig - #94 has been merged - can you rebase now?

**Comment by mwcraig** [comment]
done...

**Comment by mwcraig** [comment]
Looks like the fail is due to a relatively minor difference in array elements: https://ci.appveyor.com/project/Astropy/reproject/build/1.0.5/job/kcqcolqg6x9ppe7m#L380

**Comment by astrofrog** [comment]
@mwcraig - maybe you can increase the tolerance to 1e-5? (I wonder if the difference is due to 32- vs 64-bit?)

**Comment by mwcraig** [comment]
@astrofrog -- turns out integers are 32bit by default on Windows (at least in numpy), so I set the dtype explicitly to `np.int64` instead of changing the tolerance.

**Comment by mwcraig** [comment]
@astrofrog -- increased tolerance a bit; no idea why the tests were failing in Windows/python3.5 but not Windows/python2.7, but with these tolerance changes they pass locally.

**Comment by astrofrog** [comment]
@mwcraig - thanks!

**Pull request merged**
