### PR TITLE
Re-add the roundtrpping from #44

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by Cadair** [comment]
@astrofrog merge meeeee!

**Comment by WaaallEEE** [comment]
Ok! Thanks! Will try next week, i hardly have internet right now...

**Comment by bsipocz** [comment]
@Cadair - wouldn't this need a tests?

**Comment by astrofrog** [comment]
Ideally this does indeed need some kind of regression test to make sure we don't break it in future.

**Comment by Cadair** [comment]
*review meeeee

What has upset travis? I will try and write a test shortly.

**Comment by bsipocz** [comment]
Travis seems unrelated, e.g. #127 and probably #126 fixes a few of the failures, and someone has to when the rest, however it's probably best done once the supported astropy versions are decided.

**Comment by astrofrog** [comment]
@Cadair - looks good, but can you rebase and add a regression test?

**Comment by astrofrog** [comment]
@Cadair - I'm planning a release soon, so could you rebase and add a test? Thanks! :)

**Comment by Cadair** [comment]
Remind me on Tuesday ;)

On 15 October 2017 14:45:42 GMT-07:00, Thomas Robitaille <notifications@github.com> wrote:
>@Cadair - I'm planning a release soon, so could you rebase and add a
>test? Thanks! :)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/astrofrog/reproject/pull/129#issuecomment-336743936

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by astrofrog** [comment]
I'll go ahead and merge this as at least it doesn't break the existing tests... But a test would have been nice 😢

**Pull request merged**
