### PR TITLE
[EXP] Ignore AstropyDeprecationWarning

### PR DESCRIPTION
**Pull request by pllim**
Investigating https://github.com/astropy/astropy/pull/6334#issuecomment-313183840

### CODE REVIEW

**Comment by pllim** [comment]
@bsipocz , maybe you don't need astropy/astropy#6334 after all. Astropy dev tests pass just with this change. The only failure is Numpy 1.7, which seems unrelated to deprecation warning.

**Comment by bsipocz** [comment]
Yes, this workaround is fine if we don't have anything else. But this means that all AstropyDeprecationWarnings are ignored, even the ones that are triggered by local, reproject code, and that would be great to avoid.

**Comment by bsipocz** [comment]
Re: np 1.7, it was already agreed that version can be dropped (see #127), the PR just hasn't been merged as there are these astropy dev test failures.

**Comment by pllim** [comment]
We might not need this work around anymore. Please don't merge.

**Comment by pllim** [comment]
Don't need this anymore. :tada:

**Pull request closed without merging**
