### PR TITLE
Add round-tripping to coordinate conversion

### PR DESCRIPTION
**Pull request by astrofrog**
This needs some more comments and tests

cc @Cadair

### CODE REVIEW

**Comment by cdeil** [comment]
Is this still something that should go in?

**Comment by astrofrog** [comment]
@cdeil - eventually I think so but I need to re-examine this once the sunpy coordinates module is finally merged, since that was the use case where it was needed (cc @Cadair)

**Comment by Cadair** [comment]
*finally*.... eugh :p

**Comment by astrofrog** [comment]
@Cadair - can you try out this branch? This includes the commits from https://github.com/astrofrog/reproject/pull/102 for now. I think it should fix your issue?

test

I need to add a regression test, and see if we can extend this to also work with the full n-dimensional reproject.

**Comment by Cadair** [comment]
Awesome! I will lest later.

**Comment by Cadair** [comment]
Seems to work ok (I think we ran the same code lol)

**Comment by astrofrog** [comment]
Done in #129

**Pull request closed without merging**
