### PR TITLE
Generalize reprojection in 3 dimensions

### PR DESCRIPTION
**Pull request by keflavich**
Work was collaborative with @adonath

### CODE REVIEW

**Comment by astrofrog** [comment]
Things that need to be done before merging:

* [ ] Add checks of units etc for the full reproject
* [ ] Add unit tests for full reproject
* [ ] Fix sphinx failure

**Comment by keflavich** [comment]
Added 1x test for `_full_reproject` for the case where it matches `_reproject_celestial` on a cube.  Still needs more...

**Comment by keflavich** [comment]
I think the test coverage should now be pretty good.  There are tests that check that `_reproject_full` and `_reproject_celestial` match when they should

**Comment by keflavich** [comment]
failure is:
```
>       p_out = np.meshgrid(*p_out_ax, indexing='ij')
E       TypeError: meshgrid() takes exactly 2 arguments (4 given)
```
Suggest dropping np1.6 support, raising an Exception at this point if np<1.7 is used and putting an xfail in the tests.

**Comment by astrofrog** [comment]
Yeah, let's drop Numpy 2.6

**Comment by astrofrog** [comment]
@keflavich - at the moment, this will not do the right thing for spectral cubes that have velocity axes that use different conventions, correct? So I had an idea - what about we re-use some of the spectral-cube machinery (importing from spectral-cube, not copying) so first make sure we have the two WCS in the same exact conventions?

**Comment by astrofrog** [comment]
Hmm actually maybe what's being done here is fine since it checks CTYPE.

**Comment by astrofrog** [comment]
I'll go ahead and merge this now and we can refine in future PRs. Thanks @keflavich and @adonath!

**Comment by keflavich** [comment]
Yes I want to use the spectral cube machinery for this.   It's done in the
associated spectral cube pr.  Eventually can merge that functionality in
here.

**Pull request merged**
