### PR TITLE
Updating to package template 1.1.2

### PR DESCRIPTION
**Pull request by bsipocz**
Includes the changes of configparser for py3.5.2, and a few minor things.

### CODE REVIEW

**Comment by bsipocz** [comment]
The same question applies here for numpy1.6. Do you want to keep it in the matrix? If yes, it needs to be build with astropy1.1

**Comment by astrofrog** [comment]
Let's ditch Numpy 1.6 :)

**Comment by astrofrog** [comment]
Thanks for all the PRs!

**Comment by bsipocz** [comment]
Np, I had a procrastination fueled day. A few more, but hopefully more automated PR are on their way is I win over sed :)

**Comment by astrofrog** [comment]
Thanks @bsipocz!

**Pull request merged**
