### PR TITLE
Updating astropy-helpers and adding healpy's version to test header

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by bsipocz** [comment]
While going through old, but still open PRs, I've cleaned up this (removed travis changes that were obsolete since using ci-helpers, and upgraded the helpers not to 1.0.5 but 1.1.1).

**Comment by astrofrog** [comment]
@bsipocz - thanks! Are there any changes to ``ah_bootstrap.py`` to copy?

**Comment by bsipocz** [comment]
Yes, the True-->False change. It's included.

**Comment by astrofrog** [comment]
Ok, thanks! (was curious, since often the changes are more significant)

**Comment by cdeil** [comment]
:+1:  Merge?

**Pull request merged**
